window.JLPT_DATA = {
  meta: {
    title: "Japanese Flashcards AI Tutor",
    startDate: "2026-06-10",
    vocabCount: 6,
    grammarCount: 6,
  },
  schedule: [
    { studyDay: 1, date: "2026-06-10", newVocabUnit: "Sample Unit 01", newGrammarCards: "1-3" },
    { studyDay: 2, date: "2026-06-11", newVocabUnit: "Sample Unit 02", newGrammarCards: "4-6" },
  ],
  vocab: [
    {
      id: "sample-vocab-001",
      type: "vocab",
      level: "N5",
      day: 1,
      itemNo: 1,
      unit: "Sample Unit 01",
      front: "勉強する",
      reading: "べんきょうする",
      meaning: "to study",
    },
    {
      id: "sample-vocab-002",
      type: "vocab",
      level: "N5",
      day: 1,
      itemNo: 2,
      unit: "Sample Unit 01",
      front: "会社",
      reading: "かいしゃ",
      meaning: "company",
    },
    {
      id: "sample-vocab-003",
      type: "vocab",
      level: "N4",
      day: 1,
      itemNo: 3,
      unit: "Sample Unit 01",
      front: "面接",
      reading: "めんせつ",
      meaning: "interview",
    },
    {
      id: "sample-vocab-004",
      type: "vocab",
      level: "N4",
      day: 2,
      itemNo: 4,
      unit: "Sample Unit 02",
      front: "経験",
      reading: "けいけん",
      meaning: "experience",
    },
    {
      id: "sample-vocab-005",
      type: "vocab",
      level: "N3",
      day: 2,
      itemNo: 5,
      unit: "Sample Unit 02",
      front: "自然",
      reading: "しぜん",
      meaning: "natural",
    },
    {
      id: "sample-vocab-006",
      type: "vocab",
      level: "N3",
      day: 2,
      itemNo: 6,
      unit: "Sample Unit 02",
      front: "改善",
      reading: "かいぜん",
      meaning: "improvement",
    },
  ],
  grammar: [
    {
      id: "sample-grammar-001",
      type: "grammar",
      cardNo: 1,
      front: "~ようとする",
      readingHint: "",
      meaning: "to try to do; to be about to do",
      importance: "★★★",
    },
    {
      id: "sample-grammar-002",
      type: "grammar",
      cardNo: 2,
      front: "~ことになる",
      readingHint: "",
      meaning: "it has been decided that",
      importance: "★★★",
    },
    {
      id: "sample-grammar-003",
      type: "grammar",
      cardNo: 3,
      front: "~として",
      readingHint: "",
      meaning: "as; in the role of",
      importance: "★★★",
    },
    {
      id: "sample-grammar-004",
      type: "grammar",
      cardNo: 4,
      front: "~ようにする",
      readingHint: "",
      meaning: "to make sure to do",
      importance: "★★",
    },
    {
      id: "sample-grammar-005",
      type: "grammar",
      cardNo: 5,
      front: "~ばかりでなく",
      readingHint: "",
      meaning: "not only ... but also",
      importance: "★★",
    },
    {
      id: "sample-grammar-006",
      type: "grammar",
      cardNo: 6,
      front: "~によって",
      readingHint: "",
      meaning: "depending on; by means of",
      importance: "★★",
    },
  ],
  customDecks: {
    conversation: [
      {
        id: "sample-conversation-001",
        type: "custom",
        sourceKind: "conversation",
        sourceLabel: "Conversation",
        cardNo: 1,
        front: "最近、何を勉強していますか。",
        reading: "",
        meaning: "What are you studying recently?",
      },
      {
        id: "sample-conversation-002",
        type: "custom",
        sourceKind: "conversation",
        sourceLabel: "Conversation",
        cardNo: 2,
        front: "日本で働きたい理由は何ですか。",
        reading: "",
        meaning: "Why do you want to work in Japan?",
      },
    ],
    interview: [
      {
        id: "sample-interview-001",
        type: "custom",
        sourceKind: "interview",
        sourceLabel: "Interview",
        cardNo: 1,
        front: "自己紹介をお願いします。",
        reading: "",
        meaning: "Please introduce yourself.",
      },
      {
        id: "sample-interview-002",
        type: "custom",
        sourceKind: "interview",
        sourceLabel: "Interview",
        cardNo: 2,
        front: "これまでの経験を教えてください。",
        reading: "",
        meaning: "Please tell me about your experience so far.",
      },
    ],
  },
};
